/** The browser-facing contract for a virtual try-on request. */
export interface TryOnRequest {
  userImage: File;
  garmentImage: File;
  description: string;
}

/** The only result the UI displays: the image generated by the try-on API. */
export interface TryOnResult {
  imageUrl: string;
}

type JsonRecord = Record<string, unknown>;

function isRecord(value: unknown): value is JsonRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function toImageUrl(value: unknown): string | null {
  if (typeof value !== "string" || value.length === 0) return null;

  if (/^(https?:|data:image\/|blob:)/i.test(value)) return value;

  // Some image-generation APIs return bare base64 instead of a data URL.
  if (/^[A-Za-z0-9+/]+={0,2}$/.test(value) && value.length > 100) {
    return `data:image/png;base64,${value}`;
  }

  return null;
}

/**
 * The backend currently leaves its response schema open. Accept the common
 * response keys so a generated URL, data URL, or base64 image can all render.
 */
function findGeneratedImage(value: unknown, depth = 0): string | null {
  const directImage = toImageUrl(value);
  if (directImage || depth > 2 || !isRecord(value)) return directImage;

  const imageKeys = [
    "image_url",
    "imageUrl",
    "generated_image",
    "generatedImage",
    "result_image",
    "resultImage",
    "tryon_image",
    "tryonImage",
    "image",
    "output",
    "result",
  ];

  for (const key of imageKeys) {
    const image = findGeneratedImage(value[key], depth + 1);
    if (image) return image;
  }

  return findGeneratedImage(value.data, depth + 1);
}

async function readError(response: Response): Promise<string> {
  try {
    const payload: unknown = await response.json();
    if (isRecord(payload) && typeof payload.error === "string") return payload.error;
    if (isRecord(payload) && typeof payload.detail === "string") return payload.detail;
  } catch {
    // A non-JSON error body is still covered by the status fallback below.
  }

  return `Try-on generation failed (${response.status}).`;
}

/**
 * Send the two image files and the garment description to the local proxy.
 * The proxy forwards the request to the supplied try-on backend, preventing
 * browser CORS constraints from interrupting the upload.
 */
export async function generateTryOn(request: TryOnRequest): Promise<TryOnResult> {
  const formData = new FormData();
  formData.append("person_image", request.userImage);
  formData.append("garment_image", request.garmentImage);
  formData.append("description", request.description);

  const response = await fetch("/api/tryon", {
    method: "POST",
    body: formData,
  });

  if (!response.ok) throw new Error(await readError(response));

  // The proxy also supports an API that returns image bytes directly.
  if (response.headers.get("content-type")?.startsWith("image/")) {
    return { imageUrl: URL.createObjectURL(await response.blob()) };
  }

  const payload: unknown = await response.json();
  const imageUrl = findGeneratedImage(payload);
  if (!imageUrl) {
    throw new Error("The try-on API response did not include a generated image.");
  }

  return { imageUrl };
}
